# Generated by Django 5.2.3 on 2025-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_name_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='singer',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
