# Generated by Django 5.2.3 on 2025-07-12 15:03

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_tag_alter_singer_content_singer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.image_upload_path),
        ),
    ]
